name: Build a pdf

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@4
        with:
          node-version: "20.x"

      - name: Run 
        run: |
          sudo npm install --global wkhtmltopdf 
          wkhtmltopdf --page-size A4 cv.html cv.pdf
      
      - uses: actions/upload-artifact@4
        with:
          name: cv
          path: cv.pdf
