name: Build a pdf

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "20.x"

      - name: Run
        run: |
          sudo apt-get install -y --fix-missing wkhtmltopdf || true
          wkhtmltopdf --page-size A4 cv.html Slowikowski_Arkadiusz_Resume.pdf

      - uses: actions/upload-artifact@v6
        with:
          name: cv
          path: Slowikowski_Arkadiusz_Resume.pdf

      - name: Create Release
        run: gh release create latest Slowikowski_Arkadiusz_Resume.pdf --title "${{  github.ref_name }}"" --notes "" --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
